/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job;

/**
 *
 * 
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        feedback = new javax.swing.JLabel();
        meeting = new javax.swing.JLabel();
        personaldata = new javax.swing.JLabel();
        dailytask = new javax.swing.JLabel();
        hr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 110, 30));

        feedback.setText(" ");
        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt);
            }
        });
        getContentPane().add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 30));

        meeting.setText(" ");
        meeting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meetingMouseClicked(evt);
            }
        });
        getContentPane().add(meeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 100, 30));

        personaldata.setText(" ");
        personaldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaldataMouseClicked(evt);
            }
        });
        getContentPane().add(personaldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 140, 30));

        dailytask.setText(" ");
        dailytask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailytaskMouseClicked(evt);
            }
        });
        getContentPane().add(dailytask, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 110, 30));

        hr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/Employee.jpg"))); // NOI18N
        hr.setText(" ");
        getContentPane().add(hr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
         Home a = new Home();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseClicked
            EmployeeFeedback a = new EmployeeFeedback();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_feedbackMouseClicked

    private void meetingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meetingMouseClicked
        EmployeeMeetings a = new EmployeeMeetings();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_meetingMouseClicked

    private void personaldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaldataMouseClicked
        EmployeePersonalData a = new EmployeePersonalData();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_personaldataMouseClicked

    private void dailytaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailytaskMouseClicked
       
           EmployeeDailyTask a = new EmployeeDailyTask();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_dailytaskMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dailytask;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel hr;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel meeting;
    private javax.swing.JLabel personaldata;
    // End of variables declaration//GEN-END:variables
}
