/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job;

/**
 *
 * 
 */
public class Candidate extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Candidate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        cal = new javax.swing.JLabel();
        per = new javax.swing.JLabel();
        inter = new javax.swing.JLabel();
        jobs = new javax.swing.JLabel();
        cv = new javax.swing.JLabel();
        seajob = new javax.swing.JLabel();
        hr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setText(" ");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 110, 30));

        cal.setText(" ");
        cal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calMouseClicked(evt);
            }
        });
        getContentPane().add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, 30));

        per.setText(" ");
        per.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perMouseClicked(evt);
            }
        });
        getContentPane().add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 130, 30));

        inter.setText(" ");
        inter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interMouseClicked(evt);
            }
        });
        getContentPane().add(inter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 120, 30));

        jobs.setText(" ");
        jobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobsMouseClicked(evt);
            }
        });
        getContentPane().add(jobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 90, 30));

        cv.setText(" ");
        cv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvMouseClicked(evt);
            }
        });
        getContentPane().add(cv, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 120, 30));

        seajob.setText(" ");
        seajob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seajobMouseClicked(evt);
            }
        });
        getContentPane().add(seajob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 30));

        hr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/Candidate.jpg"))); // NOI18N
        hr.setText(" ");
        getContentPane().add(hr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calMouseClicked
           CandidateCalendar a  = new CandidateCalendar();
           a.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_calMouseClicked

    private void perMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perMouseClicked
       CandidatePersonalData a  = new CandidatePersonalData();
           a.setVisible(true);
           this.dispose();
            
    }//GEN-LAST:event_perMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
         Home a = new Home();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void interMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interMouseClicked
        CandidateInterviews a  = new CandidateInterviews();
           a.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_interMouseClicked

    private void jobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobsMouseClicked
        CandidateMyJobs a  = new CandidateMyJobs();
           a.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jobsMouseClicked

    private void cvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvMouseClicked
        CandidateCV a  = new CandidateCV();
           a.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_cvMouseClicked

    private void seajobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seajobMouseClicked
        CandidateSearchJobs a  = new CandidateSearchJobs();
           a.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_seajobMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cal;
    private javax.swing.JLabel cv;
    private javax.swing.JLabel hr;
    private javax.swing.JLabel inter;
    private javax.swing.JLabel jobs;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel per;
    private javax.swing.JLabel seajob;
    // End of variables declaration//GEN-END:variables
}
