/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teacheristas;


public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        edituser = new javax.swing.JLabel();
        editcourse = new javax.swing.JLabel();
        regfin = new javax.swing.JLabel();
        usersdash = new javax.swing.JLabel();
        adminp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 70, 30));

        edituser.setText(" ");
        edituser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edituserMouseClicked(evt);
            }
        });
        getContentPane().add(edituser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 180, 170));

        editcourse.setText(" ");
        editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editcourseMouseClicked(evt);
            }
        });
        getContentPane().add(editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 180, 170));

        regfin.setText(" ");
        regfin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regfinMouseClicked(evt);
            }
        });
        getContentPane().add(regfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 180, 170));

        usersdash.setText(" ");
        usersdash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersdashMouseClicked(evt);
            }
        });
        getContentPane().add(usersdash, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, 170));

        adminp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacheristas/AdminPage.jpg"))); // NOI18N
        adminp.setText(" ");
        getContentPane().add(adminp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usersdashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersdashMouseClicked
         AdminPageUserDash a = new AdminPageUserDash();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_usersdashMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        HomePage a = new HomePage();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void edituserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseClicked
         AdminPageEditUser a = new AdminPageEditUser();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_edituserMouseClicked

    private void editcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseClicked
       
       AdminPageEditCourse a = new  AdminPageEditCourse();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_editcourseMouseClicked

    private void regfinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regfinMouseClicked
        AdminPageReg_Fin a = new  AdminPageReg_Fin();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_regfinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminp;
    private javax.swing.JLabel editcourse;
    private javax.swing.JLabel edituser;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel regfin;
    private javax.swing.JLabel usersdash;
    // End of variables declaration//GEN-END:variables
}
