
package teacheristas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class SignupPage extends javax.swing.JFrame {

    Connection con;
        PreparedStatement pst;
        ResultSet rs;
    public SignupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginButton = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        tuser = new javax.swing.JTextField();
        tsur = new javax.swing.JTextField();
        tadd = new javax.swing.JTextField();
        tcity = new javax.swing.JTextField();
        tcountry = new javax.swing.JTextField();
        tpc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 280, 70));

        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 70, 30));

        tname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tname.setBorder(null);
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 360, 30));

        tpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tpass.setBorder(null);
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 340, 30));

        tuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tuser.setBorder(null);
        getContentPane().add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 360, 30));

        tsur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tsur.setBorder(null);
        getContentPane().add(tsur, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 360, 30));

        tadd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tadd.setBorder(null);
        getContentPane().add(tadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 360, 30));

        tcity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcity.setBorder(null);
        getContentPane().add(tcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 360, 30));

        tcountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcountry.setBorder(null);
        getContentPane().add(tcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 360, 30));

        tpc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tpc.setBorder(null);
        getContentPane().add(tpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacheristas/SignupPage.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        String username = tuser.getText();
        String password = tpass.getText();
        String name = tname.getText();
        String surname = tsur.getText();
        String address = tadd.getText();
        String city = tcity.getText();
        String country = tcountry.getText();
        String postalcode = tpc.getText();
        
        if (username.equals("") || password.equals("")|| name.equals("") || surname.equals("")||address.equals("")){
            JOptionPane.showMessageDialog(this,"Some fields are blanked, Try again!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/teacheristas","root","");
        
        pst = con.prepareStatement("insert into users (username,password,name,surname,address,city,country,postalcode) values (?,?,?,?,?,?,?,?)");
        pst.setString(1, username);
        pst.setString(2, password);
        pst.setString(3, name);
        pst.setString(4, surname);
        pst.setString(5, address);
        pst.setString(6, city);
        pst.setString(7, country);
        pst.setString(8, postalcode);
        
        pst.executeUpdate();
        
        
        
        
       
            JOptionPane.showMessageDialog(this,"Account Created successfully!");
            
            HomePage a = new HomePage();
            a.setVisible(true);
            this.dispose();
             
            
             
             
           
       
             
             
        
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(SignupPage.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(SignupPage.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        } 
    }//GEN-LAST:event_LoginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tadd;
    private javax.swing.JTextField tcity;
    private javax.swing.JTextField tcountry;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tpc;
    private javax.swing.JTextField tsur;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
