/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teacheristas;


public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public StudentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        personaldata = new javax.swing.JLabel();
        review = new javax.swing.JLabel();
        messages = new javax.swing.JLabel();
        searchcourse = new javax.swing.JLabel();
        programm = new javax.swing.JLabel();
        mycourses = new javax.swing.JLabel();
        studentpage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 70, 30));

        personaldata.setText(" ");
        personaldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaldataMouseClicked(evt);
            }
        });
        getContentPane().add(personaldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 180, 170));

        review.setText(" ");
        review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewMouseClicked(evt);
            }
        });
        getContentPane().add(review, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 180, 170));

        messages.setText(" ");
        messages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagesMouseClicked(evt);
            }
        });
        getContentPane().add(messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 180, 170));

        searchcourse.setText(" ");
        searchcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchcourseMouseClicked(evt);
            }
        });
        getContentPane().add(searchcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, 170));

        programm.setText(" ");
        programm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                programmMouseClicked(evt);
            }
        });
        getContentPane().add(programm, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 180, 170));

        mycourses.setText(" ");
        mycourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mycoursesMouseClicked(evt);
            }
        });
        getContentPane().add(mycourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 180, 170));

        studentpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacheristas/StudentPage.jpg"))); // NOI18N
        studentpage.setText(" ");
        getContentPane().add(studentpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchcourseMouseClicked
         StudentPageSearchCourse a = new StudentPageSearchCourse();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_searchcourseMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        HomePage a = new HomePage();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void personaldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaldataMouseClicked
         StudentPagePersonalData a = new StudentPagePersonalData();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_personaldataMouseClicked

    private void reviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewMouseClicked
       
       StudentPageReview a = new  StudentPageReview();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_reviewMouseClicked

    private void messagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagesMouseClicked
        StudentPageMessage a = new  StudentPageMessage();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_messagesMouseClicked

    private void programmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programmMouseClicked
        StudentPageProgramm a = new  StudentPageProgramm();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_programmMouseClicked

    private void mycoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mycoursesMouseClicked
         StudentPageMyCourses a = new  StudentPageMyCourses();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_mycoursesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logout;
    private javax.swing.JLabel messages;
    private javax.swing.JLabel mycourses;
    private javax.swing.JLabel personaldata;
    private javax.swing.JLabel programm;
    private javax.swing.JLabel review;
    private javax.swing.JLabel searchcourse;
    private javax.swing.JLabel studentpage;
    // End of variables declaration//GEN-END:variables
}
