/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teacheristas;


public class TeacherPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public TeacherPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        financial = new javax.swing.JLabel();
        students = new javax.swing.JLabel();
        mycourses = new javax.swing.JLabel();
        addcourse = new javax.swing.JLabel();
        messages = new javax.swing.JLabel();
        personaldata = new javax.swing.JLabel();
        teacherp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 70, 30));

        financial.setText(" ");
        financial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financialMouseClicked(evt);
            }
        });
        getContentPane().add(financial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 180, 170));

        students.setText(" ");
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsMouseClicked(evt);
            }
        });
        getContentPane().add(students, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 180, 170));

        mycourses.setText(" ");
        mycourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mycoursesMouseClicked(evt);
            }
        });
        getContentPane().add(mycourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 180, 170));

        addcourse.setText(" ");
        addcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcourseMouseClicked(evt);
            }
        });
        getContentPane().add(addcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 180, 170));

        messages.setText(" ");
        messages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagesMouseClicked(evt);
            }
        });
        getContentPane().add(messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 180, 170));

        personaldata.setText(" ");
        personaldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaldataMouseClicked(evt);
            }
        });
        getContentPane().add(personaldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 180, 170));

        teacherp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teacheristas/TeacherPage.jpg"))); // NOI18N
        teacherp.setText(" ");
        getContentPane().add(teacherp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcourseMouseClicked
         TeacherPageAddCourse a = new TeacherPageAddCourse();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_addcourseMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        HomePage a = new HomePage();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void financialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financialMouseClicked
         TeacherPageReg_Fin a = new TeacherPageReg_Fin();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_financialMouseClicked

    private void studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseClicked
       
       TeacherPageStudents a = new  TeacherPageStudents();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_studentsMouseClicked

    private void mycoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mycoursesMouseClicked
       TeacherPageMyCourses a = new  TeacherPageMyCourses();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_mycoursesMouseClicked

    private void messagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagesMouseClicked
        TeacherPageMessage a = new  TeacherPageMessage();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_messagesMouseClicked

    private void personaldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaldataMouseClicked
        TeacherPagePersonalData a = new  TeacherPagePersonalData();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_personaldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addcourse;
    private javax.swing.JLabel financial;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel messages;
    private javax.swing.JLabel mycourses;
    private javax.swing.JLabel personaldata;
    private javax.swing.JLabel students;
    private javax.swing.JLabel teacherp;
    // End of variables declaration//GEN-END:variables
}
