/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db2021;

/**
 *
 * @author giann
 */
public class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public Administrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemp1 = new javax.swing.JLabel();
        txtlogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcompany = new javax.swing.JLabel();
        txtempl = new javax.swing.JLabel();
        txtfield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        jLabel8.setText("SEA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel9.setText("Staff Evalutaion Application");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtemp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtemp1.setText("Employees Folder");
        txtemp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemp1MouseClicked(evt);
            }
        });
        jPanel2.add(txtemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_logout_rounded_up_20px.png"))); // NOI18N
        txtlogout.setText("Log out");
        txtlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlogoutMouseClicked(evt);
            }
        });
        jPanel2.add(txtlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Administrator Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 250, -1));

        txtcompany.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_company_20px.png"))); // NOI18N
        txtcompany.setText("Insert Company");
        txtcompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcompanyMouseClicked1(evt);
            }
        });
        jPanel1.add(txtcompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        txtempl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtempl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_employee_20px.png"))); // NOI18N
        txtempl.setText("Create Account");
        txtempl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemplMouseClicked(evt);
            }
        });
        jPanel1.add(txtempl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        txtfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtfield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_category_20px.png"))); // NOI18N
        txtfield.setText("Insert field");
        txtfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfieldMouseClicked(evt);
            }
        });
        jPanel1.add(txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcompanyMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcompanyMouseClicked1
        AdministratorCreateCompany a = new AdministratorCreateCompany();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtcompanyMouseClicked1

    private void txtlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlogoutMouseClicked
         HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtlogoutMouseClicked

    private void txtemp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemp1MouseClicked

    private void txtemplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemplMouseClicked
        AdministratorCreate a = new AdministratorCreate();
             a.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_txtemplMouseClicked

    private void txtfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfieldMouseClicked
        Companyfields a = new Companyfields();
             a.setVisible(true);
             this.dispose();
    }//GEN-LAST:event_txtfieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtcompany;
    private javax.swing.JLabel txtemp1;
    private javax.swing.JLabel txtempl;
    private javax.swing.JLabel txtfield;
    private javax.swing.JLabel txtlogout;
    // End of variables declaration//GEN-END:variables
}
