/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db2021;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author giann
 */
public class EmployeeAccountInfo extends javax.swing.JFrame {
    Connection con;
        PreparedStatement pst, pst2;
        ResultSet rs,rs2;
        

    /**
     * Creates new form HomePage
     */
    public EmployeeAccountInfo() {
        initComponents();
        edit();
    }

    
     private void edit()
    {
        String user = LoginPage.txtuser.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/db2021","root","");
            pst=con.prepareStatement("select * from user where username=? ");
            pst2=con.prepareStatement("select bio,sistatikes,certificates,awards from employee where username=? ");
            pst.setString(1, user);
            pst2.setString(1,user);
              
            
            rs=pst.executeQuery();
            rs2 = pst2.executeQuery();
            
            while(rs.next() && rs2.next())
            {
              txtuser.setText(rs.getString("username")) ;
              txtname.setText(rs.getString("name")) ;
              txtpass.setText(rs.getString("password")) ;
              txtsur.setText(rs.getString("surname")) ;
              txtdate.setText(rs.getString("reg_date")) ;
              txtmail.setText(rs.getString("email")) ;
              txttype.setText(rs.getString("type")) ;
            
              txtbio.setText(rs2.getString("bio")) ;
              txtsist.setText(rs2.getString("sistatikes")) ;
              txtcer.setText(rs2.getString("certificates")) ;
              txtaw.setText(rs2.getString("awards")) ;
            }
            
                    
                    
                    
                    
                    
                    
                    
                    } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeAccountInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        Logger.getLogger(EmployeeAccountInfo.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtlogout = new javax.swing.JLabel();
        txtaccount = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        txtaccount1 = new javax.swing.JLabel();
        txtaccount2 = new javax.swing.JLabel();
        txtaccount3 = new javax.swing.JLabel();
        txtaccount4 = new javax.swing.JLabel();
        txtaccount5 = new javax.swing.JLabel();
        txtaccount6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        txtbio = new javax.swing.JTextField();
        txtaccount7 = new javax.swing.JLabel();
        txtaccount8 = new javax.swing.JLabel();
        txtaccount9 = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtaccount11 = new javax.swing.JLabel();
        txtsur = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        txtmail = new javax.swing.JLabel();
        txttype = new javax.swing.JLabel();
        txtsist = new javax.swing.JLabel();
        txtcer = new javax.swing.JLabel();
        txtaw = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        jLabel8.setText("SEA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel9.setText("Staff Evalutaion Application");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_logout_rounded_up_20px.png"))); // NOI18N
        txtlogout.setText("Log out");
        txtlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlogoutMouseClicked(evt);
            }
        });
        jPanel2.add(txtlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        txtaccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount.setText("Password");
        jPanel1.add(txtaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        account.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        account.setText("Account Info");
        jPanel1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        txtaccount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount1.setText("Name");
        jPanel1.add(txtaccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtaccount2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount2.setText("Surname");
        jPanel1.add(txtaccount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtaccount3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount3.setText("Registration Date");
        jPanel1.add(txtaccount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtaccount4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount4.setText("Email");
        jPanel1.add(txtaccount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txtaccount5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount5.setText("Type");
        jPanel1.add(txtaccount5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        txtaccount6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount6.setText("Bio");
        jPanel1.add(txtaccount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        txtpass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 140, 30));

        txtbio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(txtbio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 210, 100));

        txtaccount7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount7.setText("Sistatikes");
        jPanel1.add(txtaccount7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        txtaccount8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount8.setText("Certificates");
        jPanel1.add(txtaccount8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        txtaccount9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount9.setText("Awards");
        jPanel1.add(txtaccount9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(51, 102, 255));
        txtname.setText(" ");
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, -1));

        txtaccount11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount11.setText("Username");
        jPanel1.add(txtaccount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtsur.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtsur.setForeground(new java.awt.Color(51, 102, 255));
        txtsur.setText(" ");
        jPanel1.add(txtsur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, -1));

        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtdate.setForeground(new java.awt.Color(51, 102, 255));
        txtdate.setText(" ");
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 160, -1));

        txtmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtmail.setForeground(new java.awt.Color(51, 102, 255));
        txtmail.setText(" ");
        jPanel1.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 140, -1));

        txttype.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txttype.setForeground(new java.awt.Color(51, 102, 255));
        txttype.setText(" ");
        jPanel1.add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 140, -1));

        txtsist.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtsist.setForeground(new java.awt.Color(51, 102, 255));
        txtsist.setText(" ");
        jPanel1.add(txtsist, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 140, -1));

        txtcer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtcer.setForeground(new java.awt.Color(51, 102, 255));
        txtcer.setText(" ");
        jPanel1.add(txtcer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 140, -1));

        txtaw.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtaw.setForeground(new java.awt.Color(51, 102, 255));
        txtaw.setText(" ");
        jPanel1.add(txtaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 140, -1));

        txtuser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtuser.setForeground(new java.awt.Color(51, 102, 255));
        txtuser.setText(" ");
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, -1));

        Update.setBackground(new java.awt.Color(51, 102, 255));
        Update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Update.setText("Update");
        Update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 50));

        Back.setBackground(new java.awt.Color(51, 102, 255));
        Back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlogoutMouseClicked
         HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtlogoutMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        String user=LoginPage.txtuser.getText();
        String password= txtpass.getText();
          String bio= txtbio.getText();
          
        
          if (txtpass.equals("") || txtbio.equals(""))
          {
              JOptionPane.showMessageDialog(null,"Password or Bio are blanked","Error",JOptionPane.ERROR_MESSAGE);
          }
          else
          {
          
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
         con = DriverManager.getConnection("jdbc:mysql://localhost/db2021","root","");
         pst=con.prepareStatement("update user set password=? where username=?");
         pst2=con.prepareStatement("update employee set bio=? where username=?");
         
          pst.setString(1,password );
          pst.setString(2,user );
          
           pst2.setString(1,bio );
          pst2.setString(2,user );
             
         pst.executeUpdate();
         pst2.executeUpdate();
         
         JOptionPane.showMessageDialog(this,"Succesful Update");
         
         Employee a = new Employee();
         a.setVisible(true);
         this.dispose();
         
         
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(EmployeeAccountInfo.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(EmployeeAccountInfo.class.getName()).log(Level.SEVERE, null, ex);
    }
          }   
    }//GEN-LAST:event_UpdateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
         Employee a = new Employee();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAccountInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Update;
    private javax.swing.JLabel account;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtaccount;
    private javax.swing.JLabel txtaccount1;
    private javax.swing.JLabel txtaccount11;
    private javax.swing.JLabel txtaccount2;
    private javax.swing.JLabel txtaccount3;
    private javax.swing.JLabel txtaccount4;
    private javax.swing.JLabel txtaccount5;
    private javax.swing.JLabel txtaccount6;
    private javax.swing.JLabel txtaccount7;
    private javax.swing.JLabel txtaccount8;
    private javax.swing.JLabel txtaccount9;
    private javax.swing.JLabel txtaw;
    private javax.swing.JTextField txtbio;
    private javax.swing.JLabel txtcer;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txtlogout;
    private javax.swing.JLabel txtmail;
    private javax.swing.JLabel txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JLabel txtsist;
    private javax.swing.JLabel txtsur;
    private javax.swing.JLabel txttype;
    private javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
