/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db2021;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author giann
 */
public class EmployeeApply extends javax.swing.JFrame {
 
        Connection con;
       PreparedStatement pst,pst2,pst3,pst4,pst5;
      ResultSet rs,rs2,rs3,rs4,rs5;
    /**
     * Creates new form HomePage
     */
    public EmployeeApply() {
       initComponents();
       company();
       job();
    }
private void company()
    {
                  
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/db2021","root","");
           
            pst=con.prepareStatement("select AFM,name from company");
            
            rs=pst.executeQuery();
            
            
            
            
            
            while(rs.next())
            {
                
                 txtcomp.addItem(rs.getString("name"));
                 
                 
            }
        }
          catch (ClassNotFoundException ex) {
          Logger.getLogger(EmployeeApply.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(EmployeeApply.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }
private void job()
    {
                   String company = (String) txtcomp.getSelectedItem();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/db2021","root","");
            pst3=con.prepareStatement("select AFM from company where name=?");
            pst3.setString(1, company);
            rs3= pst3.executeQuery();
            
             while(rs3.next())
            {
                
                 String id = rs3.getString("AFM");
                 
         
            pst2=con.prepareStatement("select position from job where firm=?");
            pst2.setString(1, id);
            
            rs2=pst2.executeQuery();
            
           while( rs2.next()){
            
            
            
             
            txtjob.addItem(rs2.getString("position"));
                 
           }
            }
        }
          catch (ClassNotFoundException ex) {
          Logger.getLogger(EmployeeApply.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(EmployeeApply.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemp1 = new javax.swing.JLabel();
        txtlogout = new javax.swing.JLabel();
        txtcompany = new javax.swing.JLabel();
        txtcompany1 = new javax.swing.JLabel();
        txtcompany2 = new javax.swing.JLabel();
        Apply = new javax.swing.JButton();
        txtjob = new javax.swing.JComboBox<>();
        txtcomp = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        jLabel8.setText("SEA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel9.setText("Staff Evalutaion Application");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtemp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtemp1.setText("Employees Folder");
        txtemp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemp1MouseClicked(evt);
            }
        });
        jPanel2.add(txtemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_logout_rounded_up_20px.png"))); // NOI18N
        txtlogout.setText("Log out");
        txtlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlogoutMouseClicked(evt);
            }
        });
        jPanel2.add(txtlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        txtcompany.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcompany.setText("Company");
        jPanel1.add(txtcompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        txtcompany1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcompany1.setText("Job");
        jPanel1.add(txtcompany1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        txtcompany2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtcompany2.setText("Apply Job");
        jPanel1.add(txtcompany2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        Apply.setBackground(new java.awt.Color(51, 102, 255));
        Apply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Apply.setText("Apply");
        Apply.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });
        jPanel1.add(Apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 150, 50));

        txtjob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtjob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjobActionPerformed(evt);
            }
        });
        jPanel1.add(txtjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 200, 30));

        txtcomp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompActionPerformed(evt);
            }
        });
        jPanel1.add(txtcomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 200, 30));

        Back.setBackground(new java.awt.Color(51, 102, 255));
        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlogoutMouseClicked
         HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtlogoutMouseClicked

    private void txtemp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemp1MouseClicked

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
         String user = LoginPage.txtuser.getText();
        String company = (String) txtcomp.getSelectedItem();
        String job= (String) txtjob.getSelectedItem();
        
        
          try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/db2021","root","");
            pst=con.prepareStatement("select AFM from company where name=?");
            pst.setString(1, company);
            rs= pst.executeQuery();
            
             while(rs.next())
            {
                
                 String afm = rs.getString("AFM");
                 
            
                 
         
            pst2=con.prepareStatement("select id from job where position=?");
            pst2.setString(1, job);
            
            rs2=pst2.executeQuery();
            
           while( rs2.next()){
            
            
            
             
           String id = rs2.getString("id");
           
            pst3=con.prepareStatement("insert into apply_job (job_id,employee_user,firm_comp)VALUES(?,?,?)");
            pst3.setString(1, id);
            pst3.setString(2, user);
            pst3.setString(3, afm);
            
             pst3.executeUpdate();

            JOptionPane.showMessageDialog(this,"You have submitted your Application!");

            Employee a = new  Employee();
            a.setVisible(true);
            this.dispose();
                 
           
            }
            }
        }
          catch (ClassNotFoundException ex) {
          Logger.getLogger(EmployeeApply.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          Logger.getLogger(EmployeeApply.class.getName()).log(Level.SEVERE, null, ex);
      }
        
        
        
        
        
    }//GEN-LAST:event_ApplyActionPerformed

    private void txtcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompActionPerformed

    private void txtjobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjobActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
         Employee a = new Employee();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeApply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JButton Back;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> txtcomp;
    private javax.swing.JLabel txtcompany;
    private javax.swing.JLabel txtcompany1;
    private javax.swing.JLabel txtcompany2;
    private javax.swing.JLabel txtemp1;
    private javax.swing.JComboBox<String> txtjob;
    private javax.swing.JLabel txtlogout;
    // End of variables declaration//GEN-END:variables
}
