/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db2021;

/**
 *
 * @author giann
 */
public class Evaluator extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public Evaluator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemp1 = new javax.swing.JLabel();
        txtlogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtjobs = new javax.swing.JLabel();
        txtaccount = new javax.swing.JLabel();
        txtsalary = new javax.swing.JLabel();
        txtempl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        jLabel8.setText("SEA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel9.setText("Staff Evalutaion Application");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtemp1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtemp1.setText("Employees Folder");
        txtemp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemp1MouseClicked(evt);
            }
        });
        jPanel2.add(txtemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_logout_rounded_up_20px.png"))); // NOI18N
        txtlogout.setText("Log out");
        txtlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlogoutMouseClicked(evt);
            }
        });
        jPanel2.add(txtlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Evaluator Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 190, -1));

        txtjobs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_company_20px.png"))); // NOI18N
        txtjobs.setText("Edit Job");
        txtjobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtjobsMouseClicked1(evt);
            }
        });
        jPanel1.add(txtjobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        txtaccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_info_20px.png"))); // NOI18N
        txtaccount.setText("Account Info");
        txtaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtaccountMouseClicked(evt);
            }
        });
        jPanel1.add(txtaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        txtsalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_get_cash_20px.png"))); // NOI18N
        txtsalary.setText("Job Dashboard");
        txtsalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsalaryMouseClicked(evt);
            }
        });
        jPanel1.add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        txtempl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtempl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_employee_20px.png"))); // NOI18N
        txtempl.setText("Insert Job");
        txtempl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemplMouseClicked(evt);
            }
        });
        jPanel1.add(txtempl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaccountMouseClicked
         Evaluator a = new Evaluator();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtaccountMouseClicked

    private void txtjobsMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjobsMouseClicked1
        HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtjobsMouseClicked1

    private void txtlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlogoutMouseClicked
         HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtlogoutMouseClicked

    private void txtsalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsalaryMouseClicked
         Evaluator a = new Evaluator();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtsalaryMouseClicked

    private void txtemp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemp1MouseClicked

    private void txtemplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemplMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemplMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evaluator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtaccount;
    private javax.swing.JLabel txtemp1;
    private javax.swing.JLabel txtempl;
    private javax.swing.JLabel txtjobs;
    private javax.swing.JLabel txtlogout;
    private javax.swing.JLabel txtsalary;
    // End of variables declaration//GEN-END:variables
}
