/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db2021;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class LoginPage extends javax.swing.JFrame {
     Connection con;
        PreparedStatement pst;
        ResultSet rs;
    
    

    /**
     * Creates new form HomePage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtemp = new javax.swing.JLabel();
        txtAdm = new javax.swing.JLabel();
        txtHome = new javax.swing.JLabel();
        txteva = new javax.swing.JLabel();
        txtman = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtemp.setText("Employee");
        txtemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtempMouseClicked(evt);
            }
        });
        jPanel2.add(txtemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        txtAdm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAdm.setText("Administrator");
        txtAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAdmMouseClicked(evt);
            }
        });
        jPanel2.add(txtAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        txtHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtHome.setText("Home");
        txtHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHomeMouseClicked1(evt);
            }
        });
        jPanel2.add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txteva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txteva.setText("Evaluator");
        txteva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtevaMouseClicked(evt);
            }
        });
        jPanel2.add(txteva, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        txtman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtman.setText("Manager");
        txtman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmanMouseClicked(evt);
            }
        });
        jPanel2.add(txtman, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 3, 18)); // NOI18N
        jLabel8.setText("SEA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel9.setText("Staff Evalutaion Application");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 260, 40));

        txtuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtuser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 260, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login Page");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("User Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a type of User:", "Administrator", "Employee", "Evaluator", "Manager" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 260, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdmMouseClicked
         LoginPage a = new LoginPage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtAdmMouseClicked

    private void txtHomeMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseClicked1
        HomePage a = new HomePage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtHomeMouseClicked1

    private void txtempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtempMouseClicked
         LoginPage a = new LoginPage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtempMouseClicked

    private void txtevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtevaMouseClicked
         LoginPage a = new LoginPage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtevaMouseClicked

    private void txtmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmanMouseClicked
        LoginPage a = new LoginPage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtmanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = txtuser.getText();
        String password = txtpass.getText();
        String type = (String) jComboBox1.getSelectedItem();
        
        
      try{
         Class.forName("com.mysql.cj.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost/db2021","root","");
         
        
         if(jComboBox1.getSelectedItem().equals("Administrator"))
         {
             pst=con.prepareStatement("select * from user where username=? and password=? and type=? ");
             pst.setString(1, username);
             pst.setString(2, password);
             pst.setString(3, type);
             rs = pst.executeQuery();
             
             if (rs.next())
          {
             JOptionPane.showMessageDialog(this,"Successful Login!");
              Administrator a = new Administrator();
             a.setVisible(true);
             this.dispose();
              
          }
          else
          {
             JOptionPane.showMessageDialog(this,"Username,password or type of user are incorrect","Error",JOptionPane.ERROR_MESSAGE); 
             txtuser.setText("");
             txtpass.setText("");
          }
      
         
         
         }else if(jComboBox1.getSelectedItem().equals("Employee"))
         {
             pst=con.prepareStatement("select * from user where username=? and password=? and type=?");
             pst.setString(1, username);
             pst.setString(2, password);
             pst.setString(3, type);
             rs = pst.executeQuery();
             
             if (rs.next())
          {
             JOptionPane.showMessageDialog(this,"Successful Login!");
             Employee a = new Employee();
             a.setVisible(true);
             this.dispose();
              
          }
          else
          {
             JOptionPane.showMessageDialog(this,"Username,password or type of user are incorrect","Error",JOptionPane.ERROR_MESSAGE); 
             txtuser.setText("");
             txtpass.setText("");
          }
      
         
         
         }
         else if(jComboBox1.getSelectedItem().equals("Evaluator"))
         {
             pst=con.prepareStatement("select * from user where username=? and password=? and type=? ");
             pst.setString(1, username);
             pst.setString(2, password);
             pst.setString(3, type);
             
             rs = pst.executeQuery();
             
             if (rs.next())
          {
             JOptionPane.showMessageDialog(this,"Successful Login!");
             Evaluator a = new Evaluator();
             a.setVisible(true);
             this.dispose();
              
              
          }
          else
          {
             JOptionPane.showMessageDialog(this,"Username,password or type of user are incorrect","Error",JOptionPane.ERROR_MESSAGE); 
             txtuser.setText("");
             txtpass.setText("");
          }
      
         
         
         }
         else if(jComboBox1.getSelectedItem().equals("Manager"))
         {
             pst=con.prepareStatement("select * from user where username=? and password=? and type=?");
             pst.setString(1, username);
             pst.setString(2, password);
             pst.setString(3, type);
             
             rs = pst.executeQuery();
             
             if (rs.next())
          {
             JOptionPane.showMessageDialog(this,"Successful Login!");
             Manager a = new Manager();
             a.setVisible(true);
             this.dispose();
          }
          else
          {
             JOptionPane.showMessageDialog(this,"Username,password or type of user are incorrect","Error",JOptionPane.ERROR_MESSAGE); 
             txtuser.setText("");
             txtpass.setText("");
          }
      
         
         
         
         
      }
         
      }catch (ClassNotFoundException ex) {
         Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
     }
        
    
    
    
        
     

  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtAdm;
    private javax.swing.JLabel txtHome;
    private javax.swing.JLabel txtemp;
    private javax.swing.JLabel txteva;
    private javax.swing.JLabel txtman;
    private javax.swing.JPasswordField txtpass;
    public static javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
